import type { DayStemKey, DeangBreed } from '@/types/deang-saju';

export const STEM_ORDER: DayStemKey[] = [
  'gap',
  'eul',
  'byeong',
  'jeong',
  'mu',
  'gi',
  'gyeong',
  'sin',
  'im',
  'gye',
];

// 오행 순서 기준 2개씩(양/음) 묶은 그룹 — 상생/상극 계산에 사용
export const ELEMENT_GROUPS: DayStemKey[][] = [
  ['gap', 'eul'],
  ['byeong', 'jeong'],
  ['mu', 'gi'],
  ['gyeong', 'sin'],
  ['im', 'gye'],
];

export const DEANG_BREEDS: Record<DayStemKey, DeangBreed> = {
  gap: {
    key: 'gap',
    stemName: '갑(甲)',
    breedName: '진돗개',
    element: 'wood',
    title: '의리 하나로 사는 진돗개',
    emoji: '🐕',
    hashtags: ['#의리하나', '#대장기질', '#주인바라기'],
    baseStats: { leadership: 9, affection: 3, perceptiveness: 6, independence: 8, attachment: 7 },
    temperament: '한번 마음먹으면 끝까지 가는 우직한 스타일이에요. 주인이 아니면 곁을 잘 안 내줘요.',
    socialStyle: '애교는 서툴지만 충성심은 넘사벽. 진심은 말이 아니라 행동으로 보여줘요.',
    loveStyle: '대시는 느리지만 한번 마음을 주면 평생 갑니다. 밀당 따위는 몰라요.',
    workStyle: '시키는 일은 완벽하게 해내지만, 야근은 절대 사양이에요.',
    quips: ['말은 없어도 뒤에서 다 챙기는 스타일.', '정 주기까지 오래 걸리지만 한번 주면 끝까지 간다.'],
  },
  eul: {
    key: 'eul',
    stemName: '을(乙)',
    breedName: '포메라니안',
    element: 'wood',
    title: '귀염뽀짝 정치견 포메라니안',
    emoji: '🦊',
    hashtags: ['#관종본능', '#애교폭격기', '#사교의달인'],
    baseStats: { leadership: 5, affection: 10, perceptiveness: 9, independence: 3, attachment: 6 },
    temperament: '작지만 존재감은 1등. 어디서든 주목받아야 직성이 풀려요.',
    socialStyle: '표정 하나로 다 표현하는 갬성 만렙. 눈치는 국가대표급이에요.',
    loveStyle: '애교로 다 무너뜨리는 스타일. 밀당의 고수예요.',
    workStyle: '분위기 메이커에 인맥왕. 다만 잔소리는 잘 못 참아요.',
    quips: ['귀여운 척이 아니라 그냥 원래 귀여움.', '애교로 안 되는 일이 없다.'],
  },
  byeong: {
    key: 'byeong',
    stemName: '병(丙)',
    breedName: '웰시코기',
    element: 'fire',
    title: '태양을 품은 웰시코기',
    emoji: '☀️',
    hashtags: ['#에너지폭발', '#뒤끝제로', '#단순왕'],
    baseStats: { leadership: 8, affection: 9, perceptiveness: 3, independence: 4, attachment: 6 },
    temperament: '가만히 못 있는 인간 에너자이저. 뒤끝은 1도 없어요.',
    socialStyle: '좋으면 좋다, 싫으면 싫다 다 티가 나요. 눈치는 살짝 부족해요.',
    loveStyle: '밀당 없는 온몸 직진 애교 수록.',
    workStyle: '아이디어 폭발, 분위기 메이커예요.',
    quips: ['가만히 있으라 하면 더 신난다.', '텐션이 곧 국력.'],
  },
  jeong: {
    key: 'jeong',
    stemName: '정(丁)',
    breedName: '파피용',
    element: 'fire',
    title: '은은한 매력 파피용',
    emoji: '🦋',
    hashtags: ['#세련미', '#조용한관종', '#디테일장인'],
    baseStats: { leadership: 6, affection: 7, perceptiveness: 8, independence: 5, attachment: 5 },
    temperament: '화려해 보이지만 은근 신중해요. 디테일 하나하나 놓치지 않아요.',
    socialStyle: '조용히 스며드는 스타일. 은근한 존재감으로 승부해요.',
    loveStyle: '은근한 스킨십과 눈빛으로 승부하는 타입.',
    workStyle: '완벽주의, 꼼꼼함으로 인정받아요.',
    quips: ['화려한데 은근 예민함.', '조용히 다 보고 있다.'],
  },
  mu: {
    key: 'mu',
    stemName: '무(戊)',
    breedName: '그레이트피레니즈',
    element: 'earth',
    title: '든든한 산 그레이트피레니즈',
    emoji: '🏔️',
    hashtags: ['#믿음직', '#과묵수호자', '#느긋함'],
    baseStats: { leadership: 7, affection: 4, perceptiveness: 5, independence: 7, attachment: 4 },
    temperament: '존재만으로 안정감을 주는 타입이에요. 웬만해선 안 흔들려요.',
    socialStyle: '말보다 행동, 곁에 있어주는 것으로 마음을 표현해요.',
    loveStyle: '급할 것 없다는 페이스. 근데 한번 지키면 끝까지 지켜요.',
    workStyle: '묵묵히 큰 그림을 담당해요. 위기에 특히 강해요.',
    quips: ['조용한데 다 든든함.', '급한 거 딱 질색.'],
  },
  gi: {
    key: 'gi',
    stemName: '기(己)',
    breedName: '시바견',
    element: 'earth',
    title: '성실한 텃밭지기 시바견',
    emoji: '🐾',
    hashtags: ['#소신있음', '#독고다이', '#은근고집'],
    baseStats: { leadership: 6, affection: 5, perceptiveness: 6, independence: 9, attachment: 5 },
    temperament: '내 구역, 내 페이스가 최우선이에요. 은근 고집불통이에요.',
    socialStyle: '츤데레의 정석. 안 좋아하는 척하면서 다 챙겨줘요.',
    loveStyle: '밀당이 아니라 그냥 내 페이스대로 가는 스타일.',
    workStyle: '시키는 대로 안 하고 내 방식대로, 결과로 증명해요.',
    quips: ['츤데레인데 계산된 츤데레 아님, 그냥 원래 그럼.', '내 방식이 곧 국룰.'],
  },
  gyeong: {
    key: 'gyeong',
    stemName: '경(庚)',
    breedName: '도베르만',
    element: 'metal',
    title: '칼같은 도베르만',
    emoji: '⚔️',
    hashtags: ['#원칙주의', '#효율끝판왕', '#카리스마'],
    baseStats: { leadership: 9, affection: 2, perceptiveness: 7, independence: 8, attachment: 3 },
    temperament: '원칙과 효율이 전부예요. 불필요한 감정 소모는 딱 질색이에요.',
    socialStyle: '표현은 짧고 굵게. 진심은 있지만 티는 잘 안 내요.',
    loveStyle: '진지하게 아니면 시작도 안 해요. 근데 진심이면 끝까지 가요.',
    workStyle: '일은 확실히 잘하는데 융통성은 살짝 부족해요. 결과로 말해요.',
    quips: ['필요한 말만 하는데 그게 다 맞는 말.', '차가운데 츤데레 아니고 그냥 쿨함.'],
  },
  sin: {
    key: 'sin',
    stemName: '신(辛)',
    breedName: '말티즈',
    element: 'metal',
    title: '새하얀 보석 말티즈',
    emoji: '💎',
    hashtags: ['#예민보스', '#완벽주의', '#품격장인'],
    baseStats: { leadership: 4, affection: 8, perceptiveness: 9, independence: 4, attachment: 7 },
    temperament: '디테일에 예민하고 기준이 확고해요. 대충 하는 건 못 참아요.',
    socialStyle: '섬세하고 예민한 편, 근데 그만큼 깊게 마음을 써요.',
    loveStyle: '예민한 만큼 세심하게 챙겨줘요. 근데 서운함은 오래가요.',
    workStyle: '완벽주의라 퀄리티는 보장, 대신 스트레스도 잘 받아요.',
    quips: ['예민한 게 아니라 기준이 높은 것.', '섬세함이 곧 자존심.'],
  },
  im: {
    key: 'im',
    stemName: '임(壬)',
    breedName: '골든리트리버',
    element: 'water',
    title: '바다 같은 골든리트리버',
    emoji: '🌊',
    hashtags: ['#품이넓음', '#인싸력만렙', '#긍정에너지'],
    baseStats: { leadership: 7, affection: 9, perceptiveness: 6, independence: 5, attachment: 4 },
    temperament: '마음이 바다처럼 넓어요. 누구든 다 품어줘요.',
    socialStyle: '감정 표현이 크고 솔직해요. 정 많고 다정해요.',
    loveStyle: '다정함이 무기예요. 상대 배려가 몸에 배어 있어요.',
    workStyle: '사람 관리 최고, 팀워크를 담당해요.',
    quips: ['정 많은 게 죄면 무기징역.', '누구한테나 다정한데 다 진심임.'],
  },
  gye: {
    key: 'gye',
    stemName: '계(癸)',
    breedName: '푸들',
    element: 'water',
    title: '이슬비 감성 푸들',
    emoji: '💧',
    hashtags: ['#똑똑함', '#센스만렙', '#은근예민'],
    baseStats: { leadership: 6, affection: 7, perceptiveness: 10, independence: 5, attachment: 6 },
    temperament: '눈치 200단, 분위기 파악 국가대표예요. 똑똑해서 계산도 빨라요.',
    socialStyle: '섬세하고 감성적이에요. 눈치껏 다 맞춰줘요.',
    loveStyle: '분위기 읽는 능력으로 상대 마음을 다 캐치해요.',
    workStyle: '센스 있게 일을 처리해요. 근데 눈치보느라 스트레스도 좀 받아요.',
    quips: ['눈치가 빠른 게 아니라 이미 다 알고 있음.', '똑똑한데 티 안 내는 스타일.'],
  },
};
