import type { TestCatalogItem } from '@/types/testCatalog';

// 모아모아 홈 화면의 단일 데이터 소스 (기존 ViralHub 인라인 ITEMS 대체)
// participantLabel / isNew / popularityRank는 큐레이션된 정적 데이터.
export const TEST_CATALOG: TestCatalogItem[] = [
  {
    id: 'sexy-battle',
    title: '색기 배틀',
    description: '사주로 페로몬 등급 판정, 나한테 꼬인 남자는 몇 명?',
    href: '/sexy-battle',
    emoji: '🔥',
    imageSrc: '/home/thumbnails/sexy-battle.jpg',
    category: 'love',
    colorTheme: 'orange',
    participantLabel: '12.4만',
    isNew: false,
    popularityRank: 2,
    editorPick: true,
    ready: true,
  },
  {
    id: 'autopsy',
    title: '사주 부검실',
    description: '전남친 사주를 부검하고 사망진단서를 발급합니다',
    href: '/autopsy',
    emoji: '🔬',
    imageSrc: '/home/thumbnails/autopsy.jpg',
    category: 'analysis',
    colorTheme: 'graphite',
    participantLabel: '8.9만',
    isNew: true,
    popularityRank: 3,
    ready: true,
  },
  {
    id: 'stock',
    title: '주가 조작단',
    description: '저평가된 연애운, 주가 조작 작전을 세워드립니다',
    href: '/stock',
    emoji: '📈',
    imageSrc: '/home/thumbnails/stock.jpg',
    category: 'money',
    colorTheme: 'slate',
    participantLabel: '6.2만',
    isNew: false,
    editorPick: true,
    ready: true,
  },
  {
    id: 'night-manual',
    title: '밤 설명서',
    description: '사주 기반 체질 평가와 시종들의 난상토론',
    href: '/night-manual',
    emoji: '🌙',
    imageSrc: '/home/thumbnails/night-manual.jpg',
    category: 'analysis',
    colorTheme: 'mist',
    participantLabel: '3.8만',
    isNew: false,
    editorPick: true,
    ready: true,
  },
  {
    id: 'dating-sim',
    title: '데이트 시뮬레이션',
    description: '사주 궁합 기반 AI 캐릭터와 5턴 데이트 대화',
    href: '/dating-sim',
    emoji: '💘',
    imageSrc: '/home/thumbnails/dating-sim.jpg',
    category: 'sim',
    colorTheme: 'graphite',
    participantLabel: '2.9만',
    isNew: true,
    editorPick: true,
    ready: true,
  },
  {
    id: 'ghost-tarot',
    title: '귀신 타로',
    description: '당신에게 붙은 귀신이 전하는 이번 달 경고, 봉인된 카드를 뽑아보세요',
    href: '/ghost-tarot',
    emoji: '👻',
    imageSrc: '/home/thumbnails/ghost-tarot.jpg',
    category: 'analysis',
    colorTheme: 'graphite',
    participantLabel: '15.2만',
    isNew: true,
    popularityRank: 1,
    ready: true,
  },
];
