import type { TestCatalogItem } from '@/types/testCatalog';

// 모아모아 홈 화면의 단일 데이터 소스 (기존 ViralHub 인라인 ITEMS 대체)
// participantLabel / isNew / popularityRank는 큐레이션된 정적 데이터.
// 2026-07-15: 귀신타로만 노출하기로 결정 — 나머지는 데이터를 지우지 않고 visibleOnHome만 false로 내림.
// 다시 노출하려면 해당 항목의 visibleOnHome을 true로 되돌리면 됨.
export const TEST_CATALOG: TestCatalogItem[] = [
  {
    id: 'sexy-battle',
    title: '색기 배틀',
    description: '사주로 페로몬 등급 판정, 나한테 꼬인 남자는 몇 명?',
    href: '/sexy-battle',
    emoji: '🔥',
    imageSrc: '/home/thumbnails/sexy-battle.jpg',
    category: 'love',
    colorTheme: 'orange',
    participantLabel: '12.4만',
    isNew: false,
    popularityRank: 2,
    editorPick: true,
    ready: true,
    visibleOnHome: false,
  },
  {
    id: 'autopsy',
    title: '사주 부검실',
    description: '전남친 사주를 부검하고 사망진단서를 발급합니다',
    href: '/autopsy',
    emoji: '🔬',
    imageSrc: '/home/thumbnails/autopsy.jpg',
    category: 'analysis',
    colorTheme: 'graphite',
    participantLabel: '8.9만',
    isNew: true,
    popularityRank: 3,
    ready: true,
    visibleOnHome: false,
  },
  {
    id: 'stock',
    title: '주가 조작단',
    description: '저평가된 연애운, 주가 조작 작전을 세워드립니다',
    href: '/stock',
    emoji: '📈',
    imageSrc: '/home/thumbnails/stock.jpg',
    category: 'money',
    colorTheme: 'slate',
    participantLabel: '6.2만',
    isNew: false,
    editorPick: true,
    ready: true,
    visibleOnHome: false,
  },
  {
    id: 'night-manual',
    title: '밤 설명서',
    description: '사주 기반 체질 평가와 시종들의 난상토론',
    href: '/night-manual',
    emoji: '🌙',
    imageSrc: '/home/thumbnails/night-manual.jpg',
    category: 'analysis',
    colorTheme: 'mist',
    participantLabel: '3.8만',
    isNew: false,
    editorPick: true,
    ready: true,
    visibleOnHome: false,
  },
  {
    id: 'dating-sim',
    title: '데이트 시뮬레이션',
    description: '사주 궁합 기반 AI 캐릭터와 5턴 데이트 대화',
    href: '/dating-sim',
    emoji: '💘',
    imageSrc: '/home/thumbnails/dating-sim.jpg',
    category: 'sim',
    colorTheme: 'graphite',
    participantLabel: '2.9만',
    isNew: true,
    editorPick: true,
    ready: true,
    visibleOnHome: false,
  },
  {
    id: 'ghost-tarot',
    title: '귀신 타로(운세편)',
    description: '당신에게 붙은 귀신이 전하는 이번 달 경고, 봉인된 카드를 뽑아보세요',
    href: '/ghost-tarot',
    emoji: '👻',
    imageSrc: '/home/thumbnails/ghost-tarot.jpg',
    category: 'analysis',
    colorTheme: 'graphite',
    participantLabel: '15.2만',
    isNew: true,
    popularityRank: 1,
    ready: true,
    visibleOnHome: true,
  },
  {
    id: 'romance-ghost-tarot',
    title: '귀신 타로(연애편)',
    description: '당신에게 붙은 존재가 전하는 인연의 신호, 카드 5장으로 확인하세요',
    href: '/romance-ghost-tarot',
    emoji: '👻',
    imageSrc: '/home/thumbnails/romance-ghost-tarot.jpg',
    category: 'love',
    colorTheme: 'graphite',
    participantLabel: '0',
    isNew: true,
    ready: true,
    visibleOnHome: true,
  },
  {
    id: 'deang-saju',
    title: '댕댕사주',
    description: '사주를 강아지로 번역, 나는 무슨 견종일까?',
    href: '/deang-saju',
    emoji: '🐾',
    imageSrc: '/home/thumbnails/deang-saju.jpg',
    category: 'analysis',
    colorTheme: 'orange',
    participantLabel: '0',
    isNew: true,
    ready: true,
    visibleOnHome: true,
  },
];
